# tcc_good_code/app/presentation/docs/user_routes.yml

tags:
  - User Routes
summary: "Obter todos os usu치rios"
description: "Endpoint para recuperar todos os usu치rios cadastrados."
responses:
  200:
    description: "Lista de usu치rios recuperada com sucesso"
    schema:
      type: array
      items:
        $ref: "#/definitions/User"
  500:
    description: "Erro ao recuperar usu치rios"
    schema:
      $ref: "#/definitions/ApiResponse"

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      age:
        type: integer
      address:
        type: string
      phone:
        type: string
      services:
        type: string
      expiration_date:
        type: string
        format: date
      notes:
        type: string

  ApiResponse:
    type: object
    properties:
      message:
        type: string
      status:
        type: integer
      data:
        type: object
      errors:
        type: object

